#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
TOOLING_CONTRACT_PATH="${TOOLING_CONTRACT_PATH:-$REPO_ROOT/docs/agents/tooling.contract.json}"
TOOLING_DOC_PATH="${TOOLING_DOC_PATH:-$REPO_ROOT/docs/agents/tooling.md}"

if ! command -v jq >/dev/null 2>&1; then
	echo "Error: jq is required to generate tooling docs."
	exit 1
fi

if [[ ! -f "$TOOLING_CONTRACT_PATH" ]]; then
	echo "Error: missing tooling contract at $TOOLING_CONTRACT_PATH"
	exit 1
fi

mkdir -p "$(dirname -- "$TOOLING_DOC_PATH")"

{
	echo "# Tooling Inventory"
	echo
	echo "<!-- Generated by scripts/generate-tooling-doc.sh from docs/agents/tooling.contract.json -->"
	echo
	echo "## Table of Contents"
	echo "- [Purpose](#purpose)"
	echo "- [Required Mise Tools](#required-mise-tools)"
	echo "- [Required Binaries](#required-binaries)"
	echo "- [Required Codex Actions](#required-codex-actions)"
	echo "- [Regeneration](#regeneration)"
	echo
	echo "## Purpose"
	echo "- Defines the repo-local tooling inventory consumed by \`scripts/check-environment.sh\`."
	echo "- Mirrors only enforced policy: required \`.mise.toml\` tools, required binaries, and required Codex actions."
	echo
	echo "## Required Mise Tools"
	while IFS= read -r tool; do
		echo "- \`$tool\`"
	done < <(jq -r '.required_mise_tools[]' "$TOOLING_CONTRACT_PATH")
	echo
	echo "## Required Binaries"
	while IFS= read -r bin; do
		echo "- \`$bin\`"
	done < <(jq -r '.required_bins[]' "$TOOLING_CONTRACT_PATH")
	echo
	echo "## Required Codex Actions"
	echo "| Action | Icon |"
	echo "| --- | --- |"
	while IFS='|' read -r name icon; do
		echo "| \`$name\` | \`$icon\` |"
	done < <(jq -r '.required_codex_actions[] | "\(.name)|\(.icon)"' "$TOOLING_CONTRACT_PATH")
	echo
	echo "## Regeneration"
	echo "Primary command:"
	echo "\`\`\`bash"
	echo "make tooling-doc"
	echo "\`\`\`"
	echo
	echo "Direct script:"
	echo "\`\`\`bash"
	echo "bash scripts/generate-tooling-doc.sh"
	echo "\`\`\`"
} > "$TOOLING_DOC_PATH"

echo "Generated $TOOLING_DOC_PATH from $TOOLING_CONTRACT_PATH"
